import { writeFile } from 'node:fs/promises'
import { type GPU, validateGPUs } from '../src/utils/schemas'

/**
 * GPU Database Refresh Script
 *
 * This script provides a template for updating GPU specs.
 * Sources:
 * - NVIDIA H100/A100: https://resources.nvidia.com/en-us-tensor-core/nvidia-tensor-core-gpu-datasheet
 * - RTX Series: https://www.nvidia.com/en-us/geforce/graphics-cards/ and TechPowerUp GPU Database
 * - AMD MI300X: https://www.amd.com/content/dam/amd/en/documents/instinct-tech-docs/data-sheets/amd-instinct-mi300x-data-sheet.pdf
 * - AMD MI325X: https://www.amd.com/content/dam/amd/en/documents/instinct-tech-docs/product-briefs/instinct-mi325x-datasheet.pdf
 * - AMD MI350X/MI355X: https://www.amd.com/content/dam/amd/en/documents/instinct-tech-docs/product-briefs/amd-instinct-mi350x-gpu-brochure.pdf
 * - Apple Silicon: Wikipedia and official Apple specs
 *
 * Update the GPUS array below with specs from official sources, then run:
 * npm run refresh:gpus
 */

const GPUS: GPU[] = [
  // NVIDIA Datacenter
  {
    id: 'nvidia-h100-80gb-pcie',
    name: 'NVIDIA H100 80GB PCIe',
    manufacturer: 'nvidia',
    vram_gb: 80,
    memory_bandwidth_gbps: 2000,
    memory_type: 'HBM3',
    bus_width: 5120,
    fp16_tflops: 989,
    fp32_tflops: 51,
    tdp_watts: 350,
    interconnect: 'nvlink-4',
    max_gpus_per_node: 8,
    tier: 'datacenter',
    spec_url: 'https://www.nvidia.com/en-us/data-center/h100/',
  },
  {
    id: 'nvidia-h100-80gb-sxm',
    name: 'NVIDIA H100 80GB SXM',
    manufacturer: 'nvidia',
    vram_gb: 80,
    memory_bandwidth_gbps: 3350,
    memory_type: 'HBM3',
    bus_width: 5120,
    fp16_tflops: 989,
    fp32_tflops: 51,
    tdp_watts: 700,
    interconnect: 'nvlink-4',
    max_gpus_per_node: 8,
    tier: 'datacenter',
    spec_url: 'https://www.nvidia.com/en-us/data-center/h100/',
  },
  {
    id: 'nvidia-h200-141gb',
    name: 'NVIDIA H200 141GB',
    manufacturer: 'nvidia',
    vram_gb: 141,
    memory_bandwidth_gbps: 4800,
    memory_type: 'HBM3e',
    bus_width: 5120,
    fp16_tflops: 989,
    fp32_tflops: 51,
    tdp_watts: 700,
    interconnect: 'nvlink-4',
    interconnect_options: ['nvlink-4', 'pcie-5'],
    max_gpus_per_node: 8,
    tier: 'datacenter',
    spec_url: 'https://www.nvidia.com/en-us/data-center/h200/',
  },
  // HGX B200 ships 1.44TB across 8 GPUs = 180GB each. 192GB is the physical
  // HBM3e stack size before reserved capacity; 180GB is the software-visible
  // figure in NVIDIA's OEM documentation and in Dell XE9680L / XE9685L and
  // Lenovo ThinkSystem listings. A VRAM calculator wants the allocatable one.
  // The id keeps its stale "192gb" suffix on purpose: changing it would break
  // every shared link naming this GPU.
  {
    id: 'nvidia-b200-192gb',
    name: 'NVIDIA B200 180GB',
    manufacturer: 'nvidia',
    vram_gb: 180,
    memory_bandwidth_gbps: 8000,
    memory_type: 'HBM3e',
    bus_width: 8192,
    fp16_tflops: 4500,
    fp32_tflops: 90,
    tdp_watts: 1000,
    interconnect: 'nvlink-5',
    max_gpus_per_node: 8,
    tier: 'datacenter',
    spec_url: 'https://www.nvidia.com/en-us/data-center/b200/',
  },
  {
    id: 'nvidia-gb300-288gb',
    name: 'NVIDIA GB300 (Blackwell Ultra) 288GB',
    manufacturer: 'nvidia',
    vram_gb: 288,
    memory_bandwidth_gbps: 8000,
    memory_type: 'HBM3e',
    bus_width: 8192,
    fp16_tflops: 5000,
    fp32_tflops: 83,
    tdp_watts: 1400,
    interconnect: 'nvlink-5',
    max_gpus_per_node: 8,
    tier: 'datacenter',
    spec_url: 'https://www.nvidia.com/en-us/data-center/gb300-nvl72/',
  },
  {
    id: 'nvidia-a100-80gb-pcie',
    name: 'NVIDIA A100 80GB PCIe',
    manufacturer: 'nvidia',
    vram_gb: 80,
    memory_bandwidth_gbps: 1935,
    memory_type: 'HBM2e',
    bus_width: 5120,
    fp16_tflops: 312,
    fp32_tflops: 19.5,
    tdp_watts: 300,
    interconnect: 'nvlink',
    max_gpus_per_node: 8,
    tier: 'datacenter',
    spec_url: 'https://www.nvidia.com/en-us/data-center/a100/',
  },
  {
    id: 'nvidia-a100-80gb-sxm',
    name: 'NVIDIA A100 80GB SXM',
    manufacturer: 'nvidia',
    vram_gb: 80,
    memory_bandwidth_gbps: 2039,
    memory_type: 'HBM2e',
    bus_width: 5120,
    fp16_tflops: 312,
    fp32_tflops: 19.5,
    tdp_watts: 400,
    interconnect: 'nvlink',
    max_gpus_per_node: 8,
    tier: 'datacenter',
    spec_url: 'https://www.nvidia.com/en-us/data-center/a100/',
  },
  {
    id: 'nvidia-l40s',
    name: 'NVIDIA L40S',
    manufacturer: 'nvidia',
    vram_gb: 48,
    memory_bandwidth_gbps: 864,
    memory_type: 'GDDR6',
    bus_width: 384,
    fp16_tflops: 366,
    fp32_tflops: 91.6,
    tdp_watts: 350,
    interconnect: 'none',
    max_gpus_per_node: 8,
    tier: 'datacenter',
    spec_url: 'https://www.nvidia.com/en-us/data-center/l40s/',
  },

  // NVIDIA Workstation/Server
  {
    id: 'nvidia-rtx-pro-6000-server',
    name: 'NVIDIA RTX PRO 6000 Server Edition',
    manufacturer: 'nvidia',
    vram_gb: 96,
    memory_bandwidth_gbps: 1597,
    memory_type: 'GDDR7',
    bus_width: 512,
    fp16_tflops: 240,
    fp32_tflops: 120,
    tdp_watts: 600,
    interconnect: 'none',
    max_gpus_per_node: 8,
    tier: 'datacenter',
    spec_url: 'https://www.nvidia.com/en-us/data-center/rtx-pro-6000-blackwell-server-edition/',
  },
  {
    id: 'nvidia-rtx-6000-ada',
    name: 'NVIDIA RTX 6000 Ada',
    manufacturer: 'nvidia',
    vram_gb: 48,
    memory_bandwidth_gbps: 960,
    memory_type: 'GDDR6',
    bus_width: 384,
    fp16_tflops: 182.2,
    fp32_tflops: 91.1,
    tdp_watts: 300,
    interconnect: 'none',
    max_gpus_per_node: 8,
    tier: 'datacenter',
    spec_url: 'https://www.nvidia.com/en-us/products/workstations/rtx-6000/',
  },

  // NVIDIA Consumer
  {
    id: 'nvidia-rtx-5090',
    name: 'NVIDIA RTX 5090',
    manufacturer: 'nvidia',
    vram_gb: 32,
    memory_bandwidth_gbps: 1792,
    memory_type: 'GDDR7',
    bus_width: 512,
    fp16_tflops: 318,
    fp32_tflops: 159,
    tdp_watts: 575,
    interconnect: 'none',
    max_gpus_per_node: 8,
    tier: 'consumer',
    spec_url: 'https://www.nvidia.com/en-us/geforce/graphics-cards/50-series/rtx-5090/',
  },
  {
    id: 'nvidia-rtx-4090',
    name: 'NVIDIA RTX 4090',
    manufacturer: 'nvidia',
    vram_gb: 24,
    memory_bandwidth_gbps: 1008,
    memory_type: 'GDDR6X',
    bus_width: 384,
    fp16_tflops: 165,
    fp32_tflops: 82.6,
    tdp_watts: 450,
    interconnect: 'none',
    max_gpus_per_node: 8,
    tier: 'consumer',
    spec_url: 'https://www.nvidia.com/en-us/geforce/graphics-cards/40-series/rtx-4090/',
  },
  {
    id: 'nvidia-rtx-3090',
    name: 'NVIDIA RTX 3090',
    manufacturer: 'nvidia',
    vram_gb: 24,
    memory_bandwidth_gbps: 936,
    memory_type: 'GDDR6X',
    bus_width: 384,
    fp16_tflops: 71,
    fp32_tflops: 35.6,
    tdp_watts: 350,
    interconnect: 'none',
    max_gpus_per_node: 8,
    tier: 'consumer',
    spec_url: 'https://www.nvidia.com/en-us/geforce/graphics-cards/30-series/rtx-3090-3090ti/',
  },
  {
    id: 'nvidia-gb300-desktop-252gb',
    name: 'NVIDIA GB300 Desktop Superchip (DGX Station)',
    manufacturer: 'nvidia',
    vram_gb: 252,
    memory_bandwidth_gbps: 7100,
    memory_type: 'HBM3e',
    bus_width: 8192,
    fp16_tflops: 5000,
    interconnect: 'nvlink-5',
    max_gpus_per_node: 1,
    tier: 'consumer',
    spec_url: 'https://www.nvidia.com/en-us/products/workstations/dgx-station/',
  },
  {
    id: 'nvidia-gb10',
    name: 'NVIDIA GB10 (DGX Spark)',
    manufacturer: 'nvidia',
    vram_gb: 128,
    memory_bandwidth_gbps: 273,
    memory_type: 'LPDDR5X',
    bus_width: 256,
    fp16_tflops: 213,
    fp32_tflops: 31,
    tdp_watts: 140,
    interconnect: 'nvlink-5',
    interconnect_options: ['nvlink-5', 'pcie-5'],
    max_gpus_per_node: 2,
    tier: 'consumer',
    spec_url: 'https://www.nvidia.com/en-us/products/workstations/dgx-spark/',
  },

  // AMD Datacenter
  {
    id: 'amd-mi355x',
    name: 'AMD Instinct MI355X',
    manufacturer: 'amd',
    vram_gb: 288,
    memory_bandwidth_gbps: 8000,
    memory_type: 'HBM3E',
    bus_width: 8192,
    // Dense FP16. AMD's headline 5.0 PFLOPS figure is with sparsity.
    fp16_tflops: 2516,
    fp32_tflops: 157,
    tdp_watts: 1400,
    interconnect: 'infinity-fabric',
    max_gpus_per_node: 8,
    tier: 'datacenter',
  },
  {
    id: 'amd-mi350x',
    name: 'AMD Instinct MI350X',
    manufacturer: 'amd',
    vram_gb: 288,
    memory_bandwidth_gbps: 8000,
    memory_type: 'HBM3E',
    bus_width: 8192,
    // Same die and memory as MI355X; the ~9% throughput gap is clocks,
    // enabled by 1400 W liquid vs 1000 W air cooling.
    fp16_tflops: 2300,
    fp32_tflops: 144,
    tdp_watts: 1000,
    interconnect: 'infinity-fabric',
    max_gpus_per_node: 8,
    tier: 'datacenter',
  },
  {
    id: 'amd-mi325x',
    name: 'AMD Instinct MI325X',
    manufacturer: 'amd',
    vram_gb: 256,
    memory_bandwidth_gbps: 6000,
    memory_type: 'HBM3E',
    bus_width: 8192,
    // Same CDNA 3 compute core as MI300X, more memory.
    fp16_tflops: 1307,
    fp32_tflops: 163,
    tdp_watts: 1000,
    interconnect: 'infinity-fabric',
    max_gpus_per_node: 8,
    tier: 'datacenter',
  },
  {
    id: 'amd-mi300x',
    name: 'AMD MI300X',
    manufacturer: 'amd',
    vram_gb: 192,
    memory_bandwidth_gbps: 5300,
    memory_type: 'HBM3',
    bus_width: 8192,
    fp16_tflops: 1307,
    fp32_tflops: 163,
    tdp_watts: 750,
    interconnect: 'infinity-fabric',
    max_gpus_per_node: 8,
    tier: 'datacenter',
    spec_url: 'https://www.amd.com/en/products/accelerators/instinct/mi300/mi300x.html',
  },

  // Apple Silicon
  {
    id: 'apple-m1-ultra',
    name: 'Apple M1 Ultra',
    manufacturer: 'apple',
    vram_gb: 128,
    memory_bandwidth_gbps: 800,
    memory_type: 'Unified',
    bus_width: 0,
    fp16_tflops: 21,
    max_gpus_per_node: 1,
    tier: 'apple-silicon',
    interconnect: 'unified',
    spec_url:
      'https://www.apple.com/newsroom/2022/03/apple-unveils-m1-ultra-the-worlds-most-powerful-chip-for-a-personal-computer/',
  },
  {
    id: 'apple-m2-ultra',
    name: 'Apple M2 Ultra',
    manufacturer: 'apple',
    vram_gb: 192,
    memory_bandwidth_gbps: 800,
    memory_type: 'Unified',
    bus_width: 0,
    fp16_tflops: 27,
    max_gpus_per_node: 1,
    tier: 'apple-silicon',
    interconnect: 'unified',
    spec_url: 'https://www.apple.com/newsroom/2023/06/apple-introduces-m2-ultra/',
  },
  {
    id: 'apple-m3-ultra',
    name: 'Apple M3 Ultra',
    manufacturer: 'apple',
    vram_gb: 192,
    memory_bandwidth_gbps: 800,
    memory_type: 'Unified',
    bus_width: 0,
    fp16_tflops: 40,
    max_gpus_per_node: 1,
    tier: 'apple-silicon',
    interconnect: 'unified',
    spec_url:
      'https://www.apple.com/newsroom/2025/03/apple-reveals-m3-ultra-taking-apple-silicon-to-a-new-extreme/',
  },
  {
    id: 'apple-m5-max',
    name: 'Apple M5 Max',
    manufacturer: 'apple',
    vram_gb: 128,
    memory_bandwidth_gbps: 614,
    memory_type: 'Unified',
    bus_width: 0,
    fp16_tflops: 35,
    max_gpus_per_node: 1,
    tier: 'apple-silicon',
    interconnect: 'unified',
    spec_url:
      'https://www.apple.com/newsroom/2026/03/apple-debuts-m5-pro-and-m5-max-to-supercharge-the-most-demanding-pro-workflows/',
  },
  {
    id: 'apple-m4-max',
    name: 'Apple M4 Max',
    manufacturer: 'apple',
    vram_gb: 128,
    memory_bandwidth_gbps: 546,
    memory_type: 'Unified',
    bus_width: 0,
    fp16_tflops: 29,
    max_gpus_per_node: 1,
    tier: 'apple-silicon',
    interconnect: 'unified',
    spec_url: 'https://www.apple.com/newsroom/2024/10/apple-introduces-m4-pro-and-m4-max/',
  },
  {
    id: 'apple-m3-max',
    name: 'Apple M3 Max',
    manufacturer: 'apple',
    vram_gb: 128,
    memory_bandwidth_gbps: 400,
    memory_type: 'Unified',
    bus_width: 0,
    fp16_tflops: 29,
    max_gpus_per_node: 1,
    tier: 'apple-silicon',
    interconnect: 'unified',
    spec_url:
      'https://www.apple.com/newsroom/2023/10/apple-unveils-m3-m3-pro-and-m3-max-the-most-advanced-chips-for-a-personal-computer/',
  },
  {
    id: 'apple-m2-max',
    name: 'Apple M2 Max',
    manufacturer: 'apple',
    vram_gb: 96,
    memory_bandwidth_gbps: 400,
    memory_type: 'Unified',
    bus_width: 0,
    fp16_tflops: 13.6,
    max_gpus_per_node: 1,
    tier: 'apple-silicon',
    interconnect: 'unified',
    spec_url:
      'https://www.apple.com/newsroom/2023/01/apple-unveils-m2-pro-and-m2-max-next-generation-chips-for-next-level-workflows/',
  },
  {
    id: 'apple-m1-max',
    name: 'Apple M1 Max',
    manufacturer: 'apple',
    vram_gb: 64,
    memory_bandwidth_gbps: 400,
    memory_type: 'Unified',
    bus_width: 0,
    fp16_tflops: 10.4,
    max_gpus_per_node: 1,
    tier: 'apple-silicon',
    interconnect: 'unified',
    spec_url:
      'https://www.apple.com/newsroom/2021/10/introducing-m1-pro-and-m1-max-the-most-powerful-chips-apple-has-ever-built/',
  },
]

async function main() {
  console.log(`Validating ${GPUS.length} GPU entries against schema...`)

  // Validate all GPUs against schema
  try {
    validateGPUs(GPUS)
    console.log('✓ All GPUs valid')
  } catch (error) {
    console.error('✗ Validation failed:', error)
    process.exit(1)
  }

  // Write to JSON file
  const outputPath = 'src/data/gpus.json'
  await writeFile(outputPath, JSON.stringify(GPUS, null, 2))
  console.log(`\n✓ Wrote ${GPUS.length} GPUs to ${outputPath}`)
}

main().catch(console.error)
